#!/bin/bash
set -u

if [ -z "$TEST_HOME" ]; then 
    echo "TEST_HOME not set."
    exit 3
fi

# if a script wants to be executed by itself, 
# it needs to load global variables
. $TEST_HOME/sbin/global_var.sh

argument_num=6
argument_num_optional=8
if [ $# -lt $argument_num ]; then
    echo "${ERRORS[$COMMAND]}[wrong_arguments]: ./sub_test [component: <namenode|datanode|journalnode>] [parameter] [value1] [value2] [reconfig_mode: <cluster_stop|online_reconfig] [waittime] optional: [read_times] [benchmark_threads]"
    exit 3
fi

# return >1 if exists command error
component=$1
parameter=$2
value1=$3
value2=$4
reconfig_mode=$5 # cluster_stop|online_reconfig
waittime=$6
read_times=10 # default value
benchmark_threads=5 # default value
n=1 # round of additional tests
if [ $# -eq $argument_num_optional ]; then
    read_times=$7
    benchmark_threads=$8
fi

if [ $reconfig_mode != "cluster_stop" ] && [ $reconfig_mode != "online_reconfig" ]; then
    echo "${ERRORS[$COMMAND]}[wrong_reconfig_mode]: reconfig_mode: cluster_stop | online_reconfig"
    exit 3
fi

# create test dir
testdir=./"$component""$split""$parameter""$split""$value1""$split""$value2""$split""$reconfig_mode""$split""$waittime"
if ! mkdir $testdir; then
    echo "${ERRORS[$COMMAND]}[cannot_mkdir]"
    exit 3
fi

# redirect logs generated by the current shell to file 
exec &> $testdir/run.log

# find out which xml file this parameter comes from
parameter_from=""
for p in $(cat $TEST_HOME/etc/parameter_hdfs.txt)
do
    if [ "$p" == "$parameter" ] ; then
	parameter_from="hdfs"
    fi
done

for p in $(cat $TEST_HOME/etc/parameter_core.txt)
do
    if [ "$p" == "$parameter" ] ; then
	parameter_from="core"
    fi
done

if [ "$parameter_from" == "hdfs" ] || [ "$parameter_from" == "core" ]; then
    echo "$parameter is from "$parameter_from"-site.xml"
    parameter_stub=nametobereplaced
    value_stub=valuetobereplaced
    cp $TEST_HOME/etc/"$parameter_from"-site-template.xml $testdir/"$parameter_from"-site.xml.1
    cp $TEST_HOME/etc/"$parameter_from"-site-template.xml $testdir/"$parameter_from"-site.xml.2
    sed -i "s/$parameter_stub/$parameter/g" $testdir/"$parameter_from"-site.xml.1
    sed -i "s/$parameter_stub/$parameter/g" $testdir/"$parameter_from"-site.xml.2
    sed -i "s/$value_stub/$value1/g" $testdir/"$parameter_from"-site.xml.1
    sed -i "s/$value_stub/$value2/g" $testdir/"$parameter_from"-site.xml.2
else
    echo "${ERRORS[$COMMAND]}[cannot_find_parameter]: cannot find $parameter in neither hdfs-site.xml nor core-site.xml"
    exit 3
fi

# main procedure
# start the cluster
echo "start cluster"
$TEST_HOME/sbin/cluster_cmd.sh start $parameter_from $testdir/"$parameter_from"-site.xml.1
sleep 5

# init client
echo "init cluster..."
wait_client_init_timeout=90
timeout $wait_client_init_timeout $TEST_HOME/sbin/cluster_cmd.sh init_client $read_times $benchmark_threads
retv=$?

if [ $retv -eq 0 ]; then
    echo "init client succeed"
else
    echo "${ERRORS[$COMMAND]}[sub_test:init_client_failure]: init client timeout: $retv"
fi

# perform reconfiguration 
if [ $reconfig_mode = "online_reconfig" ]; then
    echo "performing $reconfig_mode ..."
    $TEST_HOME/sbin/reconf.sh $component $parameter_from $testdir/"$parameter_from"-site.xml.2
    if [ $? -ne 0 ]; then
        echo "${ERRORS[$RECONFIG]}[sub_test:reconfig_component_failure]: $reconfig_mode reconfiguration $component failed"
    fi
elif [ $reconfig_mode = "cluster_stop" ]; then
    echo "performing $reconfig_mode ..."
    $TEST_HOME/sbin/reconf.sh $component $parameter_from $testdir/"$parameter_from"-site.xml.2
fi

# start benchmark running on client
$TEST_HOME/sbin/cluster_cmd.sh start_client $read_times $benchmark_threads
sleep $waittime

# stop benchmark running on client
$TEST_HOME/sbin/cluster_cmd.sh stop_client_gracefully

i=0
while [ $i -lt $n ]
do
    echo "do $(( i + 1 )) additional v1-v2" reconfig test
    # perform reconfiguration 
    if [ $reconfig_mode = "online_reconfig" ]; then
        echo "performing $reconfig_mode ..."
        $TEST_HOME/sbin/reconf.sh $component $parameter_from $testdir/"$parameter_from"-site.xml.1
        if [ $? -ne 0 ]; then
            echo "${ERRORS[$RECONFIG]}[sub_test:reconfig_component_failure]: $reconfig_mode reconfiguration $component failed"
        fi
    elif [ $reconfig_mode = "cluster_stop" ]; then
        echo "performing $reconfig_mode ..."
        $TEST_HOME/sbin/reconf.sh $component $parameter_from $testdir/"$parameter_from"-site.xml.1
    fi
    
    
    # start benchmark running on client
    $TEST_HOME/sbin/cluster_cmd.sh start_client $read_times $benchmark_threads
    sleep $waittime
    # stop benchmark running on client
    $TEST_HOME/sbin/cluster_cmd.sh stop_client_gracefully
    
    # perform reconfiguration 
    if [ $reconfig_mode = "online_reconfig" ]; then
        echo "performing $reconfig_mode ..."
        $TEST_HOME/sbin/reconf.sh $component $parameter_from $testdir/"$parameter_from"-site.xml.2
        if [ $? -ne 0 ]; then
            echo "${ERRORS[$RECONFIG]}[sub_test:reconfig_component_failure]: $reconfig_mode reconfiguration $component failed"
        fi
    elif [ $reconfig_mode = "cluster_stop" ]; then
        echo "performing $reconfig_mode ..."
        $TEST_HOME/sbin/reconf.sh $component $parameter_from $testdir/"$parameter_from"-site.xml.2
    fi
    
    # start benchmark running on client
    $TEST_HOME/sbin/cluster_cmd.sh start_client $read_times $benchmark_threads
    sleep $waittime
    # stop benchmark running on client
    $TEST_HOME/sbin/cluster_cmd.sh stop_client_gracefully

    i=$(( i + 1 ))
done

# collect logs for this test 
$TEST_HOME/sbin/cluster_cmd.sh collectlog $testdir

# stop and clean the cluster
$TEST_HOME/sbin/cluster_cmd.sh stop

exit 0
